name: xdebugd9
recipe: drupal9
config:
  webroot: web
  php: "7.4"
  debug: true
  drush: true
  config:
    php: lando/config/php.ini
services:
  appserver:
    xdebug: true
    config:
      php: lando/config/php.ini
    type: php:7.4
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
        XDEBUG_SESSION: "PHPSTORM"

